### PR TITLE
MWPW-126027 [Milo Block] Download Section

### PR DESCRIPTION
**Pull request by sharmrj**
https://jira.corp.adobe.com/browse/MWPW-126027
[Docx File](https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7Bd81913ea-de61-45fc-9428-71813c836aef%7D&action=editnew)
helpx-internal url: https://helpx-internal.corp.adobe.com/content/help/en/customer-care-office-hours/analytics/analytics-advertising.html

test url: https://download--helpx-internal--adobecom.hlx.page/content/help/en/internal/download-test

### CODE REVIEW

**Review by adeshmukh-1585 — DISMISSED** [review]

**Comment by adisharm** [comment]
Hi @sharmrj , in the current download button component in AEM we also have various button styles authored by the user, like, google store button, app store, standard, etc. Are we not supporting that with the migration to Milo. In that case this might be a design decision and we should run it by the authors. I was referencing this so that we can make the authoring experience for genesis also similar to this and thats when I noticed this difference. @adeshmukh-1585 , @praveenrv , @nkthakur48  WDYT?

**Comment by sharmrj** [comment]
> Hi @sharmrj , in the current download button component in AEM we also have various button styles authored by the user, like, google store button, app store, standard, etc. Are we not supporting that with the migration to Milo. In that case this might be a design decision and we should run it by the authors. I was referencing this so that we can make the authoring experience for genesis also similar to this and thats when I noticed this difference. @adeshmukh-1585 , @praveenrv , @nkthakur48 WDYT?

My impression was that we have different variants for the download section depending on what kind of page we're on. For example in https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=AdobeLR&title=Helpx+-%3E+Project+Franklin+%3A+Gap+Analysis we originally listed two different download sections. One for tutorial (No. 31) and one for article (No. 25). The tutorial version seems to have the 'standard button' variation from AEM. 

If needed we can implement the four variants we see in the download section in AEM. I'm not so sure it would be so straightforward to make it customizable (even more so when we consider imports). At the same time, ignoring the variants will result in imports breaking certain pages.

**Review by nkthakur48 — DISMISSED** [review]

**Comment by nkthakur48** [comment]
Could you resolve the conflict here plz @sharmrj

**Comment by sharmrj** [comment]
> Could you resolve the conflict here plz @sharmrj

@nkthakur48 done

**Review by nkthakur48 — DISMISSED** [review]

**Review by nkthakur48 — APPROVED** [review]

**Pull request merged**
